version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_USER: adminer
      MYSQL_PASSWORD: adminer
      MYSQL_DATABASE: noinch
    ports:
      - 5555:3306
    volumes:
      - db_data:/var/lib/mysql
      - db_scripts_sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 7777:8080
volumes:
  db_data:
